trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - '**/*.bicep'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: bicep-reviewer-params
  - name: CARGO_TERM_COLOR
    value: always
  - name: RUSTUP_TOOLCHAIN
    value: stable

steps:
- script: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source $HOME/.cargo/env
    rustup component add clippy
  displayName: 'Install Rust'

- script: |
    source $HOME/.cargo/env
    cargo build --release
  displayName: 'Build Bicep Reviewer'

- script: |
    source $HOME/.cargo/env

    if [ -z "$(System.PullRequest.PullRequestId)" ]; then
      echo "Error: No PullRequest ID"
      exit 1
    fi

    BINARY_PATH="$(Build.SourcesDirectory)/target/release/bicep_llm_validator"
    if [ ! -f "$BINARY_PATH" ]; then
      echo "Error: Binary not found"
      exit 1
    fi

    ORG_NAME=$(echo "$(System.CollectionUri)" | sed -E 's@.*/dev\.azure\.com/([^/]+).*@\1@')
    echo "Detected Organization: $ORG_NAME"

    "$BINARY_PATH" azure \
      --organization "$ORG_NAME" \
      --project "automation" \
      --pull-request-id "$(System.PullRequest.PullRequestId)" \
      --pat "$(ADO_PAT)" \
      --best-practices-file "$(Build.SourcesDirectory)/bicep-best-practices.md" \
      --minimum-severity 3 \
      --repository "bicep-reviewer" \
      --simple
  env:
    ADO_PAT: $(ADO_PAT)
    AZURE_OPENAI_ENDPOINT: $(AZURE_OPENAI_ENDPOINT)
    AZURE_OPENAI_API_KEY: $(AZURE_OPENAI_API_KEY)
    AZURE_OPENAI_DEPLOYMENT: $(AZURE_OPENAI_DEPLOYMENT)
    AZURE_SEARCH_ENDPOINT: $(AZURE_SEARCH_ENDPOINT)
    AZURE_SEARCH_ADMIN_KEY: $(AZURE_SEARCH_ADMIN_KEY)
    AZURE_SEARCH_INDEX: $(AZURE_SEARCH_INDEX)
  displayName: 'Run Bicep Review'
